In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

In [4]:
np.random.rand(3, 2) 
np.random.random((3,2))

array([[ 0.51764651,  0.27938774],
       [ 0.35768191,  0.5762846 ],
       [ 0.28399674,  0.93991395]])

In [6]:
out1 = np.random.randn(1000, 1000)
out2 = np.random.standard_normal((1000, 1000))
out3 = np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))
assert np.allclose(np.mean(out1), np.mean(out2), atol=0.1)
assert np.allclose(np.mean(out1), np.mean(out3), atol=0.1)
assert np.allclose(np.std(out1), np.std(out2), atol=0.1)
assert np.allclose(np.std(out1), np.std(out3), atol=0.1)
print (np.mean(out3))
print (np.std(out1))

-0.000690660829093
1.00038224215


In [7]:
np.random.randint(0, 4, (3, 2))

array([[2, 0],
       [1, 1],
       [1, 0]])

In [8]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [10]:

for _ in range(10):
    print (np.random.choice(x, p=[.3, .5, .2]))

b'2 out of 10'
b'5 out of 10'
b'5 out of 10'
b'5 out of 10'
b'3 out of 10'
b'2 out of 10'
b'5 out of 10'
b'3 out of 10'
b'5 out of 10'
b'5 out of 10'


In [11]:
np.random.choice(10, 3, replace=False)

array([5, 6, 8])

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print (x)

[9 0 1 2 5 7 4 3 6 8]


In [13]:
print (np.random.permutation(10))

[1 5 4 9 7 3 2 6 0 8]
